[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
log = "0.4.27"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3.70"
features = [
    "Window",
    "Location",
]
