[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
actix-web = "4.11.0"
actix-files = "0.6.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.19"
